"""Versioned response contracts for platform agents."""

from typing import Literal

from pydantic import BaseModel, Field


class SuggestedAction(BaseModel):
    """Action hint that backend/UI may execute after policy checks."""

    name: str = Field(min_length=1, max_length=64)
    label: str = Field(min_length=1, max_length=128)
    payload: dict[str, str] = Field(default_factory=dict)


class SafetyFlag(BaseModel):
    """Safety signal generated by the skill."""

    code: str = Field(min_length=1, max_length=64)
    severity: Literal["info", "warn", "critical"] = "info"
    message: str = Field(min_length=1, max_length=256)


class AgentResponse(BaseModel):
    """Top-level response envelope returned by the platform."""

    version: Literal["v1"] = "v1"
    skill: str
    assistantText: str
    intent: str
    confidence: float = Field(ge=0, le=1)
    suggestedActions: list[SuggestedAction] = Field(default_factory=list)
    uiHints: dict[str, str] = Field(default_factory=dict)
    safetyFlags: list[SafetyFlag] = Field(default_factory=list)
